### PR TITLE
Update Transifex link 

### PR DESCRIPTION
**Pull request by horus68**
Fixing the Transifex link to point directly to the translation project

### CODE REVIEW

**Comment by gyuris** [comment]
@horus68, I suggest to submit this patch directly to core developers: https://bugs.scribus.net/ Create a new issue and attach this patch.

**Comment by aoloe** [comment]
this repository is very old, never has been an official scribus repository and is not maintained anymore.

i will accept this patch and the archive the repository.

**Comment by aoloe** [comment]
applying the patch

**Comment by aoloe** [comment]
somehow, i could not apply the match but had to manually edit the file.

it's now done.

**Pull request closed without merging**
